config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login',   to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/contact', to: 'static_pages#contact'
  get '/signupsuccess', to: 'users#success'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  resources :posts
  resources :users
  resources :account_activations, only: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :title, presence: true
  validates :subject, presence: true
  validates :email, presence: true 
  validates :author, presence: true
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  
  def self.search(search)
    where("title LIKE ? OR author LIKE ? OR isbn LIKE ? OR subject LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest
  
  has_many :posts
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(attribute,token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end
    
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
    def edit
        user = User.find_by(email: params[:email])
        if user && !user.activated? && user.authenticated?(:activation, params[:id])
            user.activate
            user.update_attribute(:activated,    true)
            user.update_attribute(:activated_at, Time.zone.now)
            log_in user
            flash[:success] = "Account activated!"
            redirect_to user
        else
          flash[:danger] = "Invalid activation link"
          redirect_to root_url
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    
    
    def new
        @post = current_user.posts.build if logged_in?
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
          redirect_to @post
        else
          render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to posts_path
    end
    
    def index
        @posts = Post.all
        @user = current_user
        if params[:search]
            @posts = Post.search(params[:search]).order("created_at DESC")
        else
            @posts = Post.all.order("created_at DESC")
        end
    end
    
    def create
        @post = current_user.posts.build(post_params)
    
        if @post.save
          redirect_to @post
        else
          render 'new'
        end
    end
    
    def show
        @post = Post.find(params[:id])
    end
    

  private
  
  def post_params
    params[:post].permit(:id,:title,:author,:isbn,:subject,:description,:email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to root_path
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def success
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      UserMailer.account_activation(@user).deliver_now
      redirect_to '/signupsuccess'
    else
      render 'new'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end
    
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title='')
        base_title = "DA Book Exchange"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt:user.name, class: "gravatar")
    end
    

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "DA Book Exchange", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path, id:"links" %></li>
        

        <% if logged_in? %>
          <li><%= link_to "Books", posts_path, id:"links" %></li>
          <li><%= link_to "Profile", current_user,id:"links" %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Log out", logout_path, method: :delete, id:"links" %>
          </li>

        <% else %>
          <li><%= link_to "Log in", login_path, id:"links" %></li>
        <% end %>
        
        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :author %><br>
  <%= f.text_field :author %>
</p>

<p>
  <%= f.label :isbn, "ISBN (optional)" %><br>
  <%= f.text_field :isbn %>
</p>
<p>
  <%= f.label :subject %><br>
<%= f.select(:subject) do %>
  <% ['Algebra I/II','Biology','Calculus','Chemistry','Chinese','Computer Science','Economics','English', 'Environmental Science','Fine Arts','French','Geometry','History','Latin','Music Theory','Physics','Post-Calculus','Precalculus','Psychology','Spanish','Statistics','Other'].each do |c| %>
    <%= content_tag(:option, c, value: c) %>
  <% end %>
<% end %>
</p>
<p>
  <%= f.label :description, "Description (condition, price, etc)" %><br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>
<p>
  <%if yield(:title) == "New Listing" %>
    <%= f.submit "Create Listing", class: "btn btn-primary btn-lg" %>
  <%else%>
    <%= f.submit "Edit Listing", class: "btn btn-primary btn-lg" %>
  <%end%>
</p>
 
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
 
  
<div class = "panel panel-default" align="left">
    <div class = "panel panel-default">
        <b>Title: </b><%= post.title %><br>
        <b>Author: </b><%= post.author %><br>
        <b>ISBN: </b><%= post.isbn %><br>
        <b>Subject: </b><%= post.subject %><br>
    </div>
    <div class = "panel panel-body">
        <b>Description: </b><%= post.description %><br>
    </div>
    <div class = "panel panel-footer">
      <b>Owner Email: </b><%= post.email %><br>
      Posted <%= time_ago_in_words(post.created_at) %> ago.
    </div>
</div>

<%if false %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content"><%= post.description %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
<%end%>
 
</li>

app/views/posts/edit.html.erb
<% provide(:title,"Edit Listing") %>
<%if @post.user_id == current_user.id %>
    <h1>Edit Listing</h1>
    <%= render 'form'%>
<%else%>
    <div align="center">
    <h3>You cannot edit this post.
    <br>
    <br>
    <%= link_to "Back to books", posts_path %>
    </h3>
    </div>
<%end%>

app/views/posts/index.html.erb
<% provide(:title,"Index")%>
<h1>Books</h1>

<div align="center">
<%= link_to "<button type = \"button\" class= \"btn btn-lg btn-primary\">Add</button>".html_safe, 'posts/new'%></button>
<br><br>
<b>Search by book, author, subject, or ISBN:</b>
<div class = "box">
<%= form_tag(posts_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Books" %>
    <%= submit_tag "Search", :name => nil, class:"btn btn-primary" %>
<% end %>
</div>
<% if request.original_url.include? "search"%>
  <%= link_to "All books", posts_path, class:"btn btn-primary"%>
<%end%> <br><br>
<% if @posts.blank? %>
  <h4>There are no books containing the term <%= params[:search] %>.</h4>
  <h3><%= link_to "Back to books", posts_path%></h3>
<%else%>
<table class = "table table-hover table-striped">
  <tr>
    <th>Book</th>
    <th>Author</th>
    <th>Subject</th>
    <th>Owner Email</th>
    <th colspan="4"></th>
  </tr>

  <% @posts = @posts.sort_by { |a| [a.subject,a.title.downcase]} %>
  
  <% @posts.map do |post| %>
    <% splittext = post.title.split(" ") %>
    <% splittext.map do |word| %>
      <% word[0] = word[0].capitalize %>
    <% end %>
    <% post.title = splittext.join(" ") %>
    <% splittext = post.author.split(" ") %>
    <% splittext.map do |word| %>
      <% word[0] = word[0].capitalize %>
    <% end %>
    <% post.author = splittext.join(" ") %>
  <% end %>
  

  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= post.author %></td>
      <td><%=post.subject%></td>
      <td><%= post.email %></td>
    <% if post.user_id == @user.id %>
      <td>&nbsp;<%= link_to 'Edit', edit_post_path(post) %></td>
      <td>&nbsp;<%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    <%else%>
      <td></td>
      <td></td>
    <%end%>
    </tr>
  <% end %>
</table>
</div>
<% end %>
<% else %>

app/views/posts/new.html.erb
<% provide(:title,"New Listing") %>
<h1>New Listing</h1>
<% if logged_in? %>
    <%= render 'form' %>
<% else %>
    <center><h3>Please <%=link_to "log in", login_path%>. </h3></center>
<%end%>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>

  
<h1><i><%= @post.title %></i></h1>
<h2>posted by <%= @post.user.name%></h2>
<div class = "panel panel-default">
  <div class = "panel panel-default">
    <b>Title: </b><%= @post.title %><br>
    <b>Author: </b><%= @post.author %><br>
    <b>ISBN: </b><%= @post.isbn %><br>
    <b>Subject: </b><%= @post.subject %><br>
  </div>
  <div class = "panel panel-body">
    <b>Description: </b><%= @post.description %><br>
  </div>
<div class = "panel panel-footer">
  <b>Owner Email: </b><%= @post.email %><br>
</div>
</div>
<h3><%= link_to 'Back to books', posts_path %></h3>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact me at
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>DA Book Exchange</h1>
  <% if !logged_in? %>
  <h2>
    <font color="CFFFFF">Tired of selling back your 150 dollar books for ten bucks?</font><br><br>
    <font color = "83E7FE">Did you buy books for a class you ended up dropping?</font><br><br>
    <font color ="4BA4D0">Want another way to get rid of your old textbooks?</font><br><br>
  </h2>
  <% else %>
  <h2>
    Welcome!
  </h2>
  <%end%>
  <% if !logged_in? %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <%else%>
    <%= link_to "Go to Books", posts_path, class: "btn btn-lg btn-primary cool-btn" %>
  <%end%>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    
        <%= render 'shared/error_messages'%>
        <p>
            <%= f.label :name%>
            <%= f.text_field :name, class: 'form-control'%>
        </p>
        <p>
            <%= f.label :email%>
            <%= f.email_field :email, class: 'form-control'%>
        </p>
        <p>
            <%= f.label :password%>
            <%= f.password_field :password, class: 'form-control'%>
        </p>
        <p>
            <%= f.label :password_confirmation, "Password Confirmation"%>
            <%= f.password_field :password_confirmation, class: 'form-control'%>
        </p>
        <br>
      <div align="center"><%= f.submit "Create My Account", class: "btn btn-primary btn-lg" %></div>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class = "row">
  <aside class = "col-md-4">
    <section class = "user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  
  <div class="col-md-8" align="center">
    <% if @user.posts.any? %>
      <h3>Available Books (<%= @user.posts.count %>)</h3>
      <ul style="list-style-type:none">
        <%= render @user.posts %>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/success.html.erb
<div align = "center">
<h1>Success!</h1>
<h3>Please check your email to activate your account.</h3>
<h3><%= link_to "Back to home", root_path %></h3>
</div>